### ISSUE TITLE
Add django-media-bundler to the Python Package Index

### ISSUE THREAD

**Issue by ask** [rnk/django-media-bundler#2]
To use django apps as distutils dependencies is the "good thing to do", so it would be nice if django-media-bundler was registered up at PyPI and could be installed using the regular tools.

**Comment by rnk** [comment]
I'm glad people think this is worth distributing further.  I registered it here:
http://pypi.python.org/pypi/django-media-bundler/0.3

I've never distributed a package before, so I'm not really familiar with the "regular tools".
